# Generated by Django 4.0.3 on 2024-09-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0003_doit_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
