# Generated by Django 4.0.3 on 2024-09-08 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0004_alter_doit_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='deadline',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
