# Generated by Django 4.0.3 on 2024-09-08 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0005_alter_doit_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='deadline',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
