# Generated by Django 4.0.3 on 2024-09-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0007_doit_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='doit',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
