# Generated by Django 4.0.3 on 2024-09-10 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0008_doit_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doit',
            name='done',
        ),
    ]
