# Generated by Django 4.0.3 on 2024-09-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0009_remove_doit_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='doit',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
