# Generated by Django 4.0.3 on 2024-09-11 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dodo', '0010_doit_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doit',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
